### PR TITLE
Add Fortran

### PR DESCRIPTION
**Pull request by jordan4ibanez**
This is a port to Fortran from C.

### CODE REVIEW

**Comment by Auburn** [comment]
Thanks for the work!
Do you have any notes on the port, are all the features fully implemented?

**Comment by jordan4ibanez** [comment]
> Thanks for the work! Do you have any notes on the port, are all the features fully implemented?

I actually had one question. What does the ``gain`` setting do in the ``fnl_state`` struct?

**Comment by Auburn** [comment]
It is the relative amplitude of each octave in a fractal

**Comment by jordan4ibanez** [comment]
> It is the relative amplitude of each octave in a fractal

Ah okay, well, then everything is in order! It should be good to go as this is a 1 to 1 translation.

**Comment by Auburn** [comment]
Do you want to add yourself to the readme credits in the PR too

**Comment by jordan4ibanez** [comment]
Yes, I am just going to make one small change as the modern fortran extension does not like seeing bind(c) enumerators, should take a few minutes.

**Comment by jordan4ibanez** [comment]
I think everything is now finished. :)

**Comment by jordan4ibanez** [comment]
Also, would you like for me to do a squash on this?

**Comment by Auburn** [comment]
No need, I can do it when I merge

**Pull request merged**
