### PR TITLE
[Rust] Added clone derive for `FastNoiseLite` 

### PR DESCRIPTION
**Pull request by DanielDK05**
"It ain't much, but it's honest work"

Added a clone derive, as cloning is necessary in some cases.

N.B: the other changes in the file came from `cargo fmt`

### CODE REVIEW

**Comment by Auburn** [comment]
@Keavon does this look good to you?

**Comment by Keavon** [comment]
Yep, this looks sensible. While we're at it, @DanielDK05 are there any other traits this ought to implement? I'm thinking probably not to `Copy` since it's a somewhat large struct (48 bytes) and the default *move* semantics would be preferable for performance reasons.

**Comment by DanielDK05** [comment]
Yeah I agree with not adding `Copy`. `Debug` might be useful at some point though. Maybe we could also do `Serialize`/`Deserialize` from `serde`, in case anyone would want to have noise configured in a file. 

I also thought of `Send` & `Sync` for multithreading, but I haven't done much multithreading in rust, so I'm not totally sure how to safely implement that.
I know it's often done simple like this:
```rust
unsafe impl Send for FastNoiseLite {}
unsafe impl Sync for FastNoiseLite {}
```
But the `unsafe` makes me nervous to implement it myself :D

**Comment by DanielDK05** [comment]
Yeah okay, I'll look at `Debug`.

**Review by Keavon — APPROVED** [review]

**Comment by Keavon** [comment]
Looks good. @Auburn should this also bump the Rust crate's minor version or will you do that in a commit to master after this PR is merged?

**Comment by Auburn** [comment]
This was also mentioned as a potential change, don't know if we want that but should wait on it before the version if so https://github.com/Auburn/FastNoiseLite/issues/137

**Pull request merged**
