### PR TITLE
Added PowerShell port

### PR DESCRIPTION
**Pull request by gregoryfmartin**
Greetings @Auburn!

I have a need for a noise generation library for a text-based terminal game that I've been working on in PowerShell and your library caught my attention. While I could have, though some level of indirection, imported the raw C# code into PowerShell, there's some oddities about using symbols from the C# code in the PowerShell code that imports it. Having said that, I felt like I couldn't do worse than to transcribe the C# code into a "PowerShell-native" dialect, taking only the necessary liberties to facilitate the constraints of PowerShell.

For tests, I also transcribed the test snippet from the C# readme to PowerShell. It looks like the following:

```
[FastNoiseLite]$Noise = $null
Try {
    $Noise = [FastNoiseLite]::new()
} Catch {
    Write-Error "$($_.Exception.Message)"
    Write-Error "$($_.Exception.StackTrace)"
    Exit
}
$Noise.SetNoiseType([FnlNoiseType]::OpenSimplex2)

$TestNoise = New-Object 'Single[,]' 128, 128

For([Int]$X = 0; $X -LT 128; $X++) {
    For([Int]$Y = 0; $Y -LT 128; $Y++) {
        $TestNoise[$X, $Y] = $Noise.GetNoise($X, $Y)
    }
}

Write-Host "$($TestNoise)"
```

That said, I've not tested this extensively other than this test here and some basic use cases within the context of the aforementioned game program, but I believe it's transcribed accurately.

I'm not sure this port would have a tremendous number of use cases, but I figured I'd throw it out there as a possibility.

### CODE REVIEW

**Comment by snowfoxsh** [comment]
PowerShell port is diabolical :skull:

Pretty cool none the less :)

**Comment by Auburn** [comment]
What an unexpected port! I'm surprised the syntax is mostly normal looking 😅 

Is it not possible to keep Int32 types instead of Int64, does powershell throw exceptions on overflow?

I would also avoid storing the pre computed bitshifted variables as static variables, just do the calculation and change the constant

**Comment by gregoryfmartin** [comment]
> What an unexpected port! I'm surprised the syntax is mostly normal looking 😅
> 
> Is it not possible to keep Int32 types instead of Int64, does powershell throw exceptions on overflow?
> 
> I would also avoid storing the pre computed bitshifted variables as static variables, just do the calculation and change the constant

Thanks for the feedback!

With regard to overflow, PowerShell will throw an exception (InvalidOperation I believe is what's thrown; I'd need to rollback a few commits and rerun the code to see which one it is specifically) which will halt the script execution. PowerShell doesn't offer explicit use of checked/unchecked statements, so AFAIK there's no protections other than exception throwing. Not the most elegant thing in the world, but that was the motivator to use Int64 explicitly.

No problem on the pre computing of the bit shifts. Some of the motivator was reducing literal use in code, but the other was performance. As it stands now, PowerShell's Measure-Command will report on average ~1.9sec. for execution with everything precomputed. I don't think there's going to be any penalty for not pre computing the bit shifts, at least any that would matter, so I can revert those. The other precomputed expressions do offer some modest performance gains, but those too are not something I'm married to.

**Comment by gregoryfmartin** [comment]
I've made the modifications to the class, as well as added a readme. I was surprised to see that not storing the bit shifts actually increased the overall performance of the class by ~500ms on average so the runs are now down to ~1.2s. I thought this would have the opposite effect.

**Comment by Auburn** [comment]
In your performance testing how many points are you generating and what noise  type?

**Comment by gregoryfmartin** [comment]
Thus far I've only used OpenSimplex2 with a 128x128 grid. I'm planning to stress the other methods later this week with larger grid sizes, but I'm not even sure I'd need something larger than 128x128 for my use case.

**Comment by Auburn** [comment]
oh wow that is slow, for reference the C++ version does about 70 million points per second.

**Pull request merged**
