### PR TITLE
Fix example code in README.md

### PR DESCRIPTION
**Pull request by arash28134**
The for loop in example code is wrong, since the index always stays at 0 and results in all 0.0 values

### CODE REVIEW

**Comment by Auburn** [comment]
The index doesn't stay at zero the ++ operator increments it

**Comment by arash28134** [comment]
> The index doesn't stay at zero the ++ operator increments it

But you're missing the first index (0), since in the first loop it'll pass 1 to  noiseData[].

**Comment by Auburn** [comment]
`index++` returns the current value then increments it, `++index` would increment first and return the incremented value.

https://en.cppreference.com/w/cpp/language/operator_incdec

**Comment by arash28134** [comment]
> `index++` returns the current value then increments it, `++index` would increment first and return the incremented value.
> 
> https://en.cppreference.com/w/cpp/language/operator_incdec

Yes you're right; my apologies.

**Pull request closed without merging**
